name: unmei_fl
description: Nonel App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  # dio: ^3.0.10
  # cookie_jar: ^1.0.0
  # dio_cookie_manager: ^1.0.0
  shared_preferences: ^2.0.5

  url_launcher: ^5.5.2
  shimmer: ^1.1.2
  persistent_bottom_nav_bar: ^3.1.0
  # provider: ^4.3.2
  # hive: ^1.4.4+1

  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  equatable: ^1.2.5

  fluttertoast: ^7.1.1
  flutter_svg: ^0.21.0-nullsafety.0
  adaptive_theme: ^2.0.0
  intl: ^0.17.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: 'assets/images/favicon.png'
  image_path_android: 'assets/images/favicon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/